### ISSUE TITLE
can't login after installation

### ISSUE THREAD

**Issue by AshkanMesbah** [kimios/kimios#14]
I have just installed kimios 1.2 tomcat bundle on ubuntu. After installtaion I am redirected to login page asking for user, password and domain name. Domain name has been already set to kimios but when I enter temp user (admin) and password (kimios), I receive "Invalid authentication". What is the problem?

**Comment by AshkanMesbah** [comment]
Thanks, will try

**Comment by devtom30** [comment]
Try kimios2019 as password. 
The admin user's default password is 'kimios' concatenated to the year of installation.

**Comment by bgone1969** [comment]
Hi,

I just installed Kimios but cannot login with admin account

**Comment by bgone1969** [comment]
> Hi,
> 
> I just installed Kimios but cannot login with admin account

Just try with password for this year 2020 and successfully, this is kimios2020
