### ISSUE TITLE
Cannot connect to localhost:9999/kimios

### ISSUE THREAD

**Issue by tsuiwingyin** [kimios/kimios#15]
I am a beginner in programming and I face a problem which looks like stupid.
I installed Java 8, Apache Tomcat etc. I can run "kimios.bat start" successfully, however, I cannot connect to localhost:9999/kimios. I note that localhost:8080 can be connected, so seems it is not the problem of Tomcat.

I have no idea about that......

**Comment by devtom30** [comment]
Ok, no problem, you're welcome.
Maybe the environment variable CATALINA_HOME is not set properly. You may also have an other Tomcat server running. 
You must set this variable before running the bundle. You are working on Windows, so you have to run this command in the same directory as kimios.sh script: 
`SET CATALINA_HOME="%cd%"`
where %cd% is the variable containing the current directory

**Comment by tsuiwingyin** [comment]
Thanks for your reply!
I think I should have an other Tomcat server running, I set CATALINA_HOME to Tomcat before.

Once I changed the environment variable (shown in the screenshot), Tomcat said that it failed to start. Please assist :(
<img width="720" alt="1" src="https://user-images.githubusercontent.com/46432962/50753078-7e495500-128b-11e9-965d-6ac172dc94bd.PNG">
<img width="876" alt="2" src="https://user-images.githubusercontent.com/46432962/50753080-7e495500-128b-11e9-9970-858f74387d3d.PNG">

**Comment by tsuiwingyin** [comment]
There's the error message shown in Tomcat window. Sorry for having some Trad. Chinese characters :)
[Tomcat.txt](https://github.com/kimios/kimios/files/2731693/Tomcat.txt)

**Comment by tsuiwingyin** [comment]
I am still searching for a solution, and I tried Kimios 1.0/1.1/1.2, similar problems happened.
Tomcat runs successfully only when I use Apache Tomcat downloaded online. 😢

**Comment by kabhinav25** [comment]
Edit the file kimios.bat.
Edit line no:  34 from:
`set JAVA_OPTS=%$JAVA_OPTS% -Dlogback.configurationFile=kimios_home/server/conf/logback.xml`
to 
`set JAVA_OPTS=%JAVA_OPTS% -Dlogback.configurationFile=kimios_home/server/conf/logback.xml`

Save and try running again.

**Comment by devtom30** [comment]
Thank you @kabhinav25 !
This was the correction
