### ISSUE TITLE
Can not get org.kimios.utils.version.Version

### ISSUE THREAD

**Issue by wanglei7** [kimios/kimios#19]
I try to start the project on IDEA,but can not get the package org.kimios.utils.version.Version.

**Comment by devtom30** [comment]
Build the project, it will create the file.

**Comment by wanglei7** [comment]
Thank you.But now I don't know how to start the project because it reports errors.
java.lang.ClassNotFoundException: org.kimios.deployer.web.AppContextLoaderListener.

**Comment by wanglei7** [comment]
Thanks for your reply.I'm sorry I have another problem.
The project starts successfully but the page directs to the install and when i click the install button it calls 
communications link failure.
