### ISSUE TITLE
 is further developed?

### ISSUE THREAD

**Issue by Xarkam** [kimios/kimios#2]
2 years without commit.

Kimios is it still maintained?

**Comment by Xarkam** [comment]
Hi,
any new on next git sync ?

**Comment by sce144** [comment]
Is there any activitiy in this project?
It seems very interesting. 
What about a german translation?

**Comment by JaredNJames** [comment]
Any updates?  Very interesting project.

**Comment by lantian** [comment]
Hi, could you please provide an update? Coz version 1.1 at download section differ from master's version.

**Comment by boblowski** [comment]
Does anyone familiar with this project know what the current status is? The product website and demo site are still available, but it looks like the project is abandoned.

**Comment by farfou** [comment]
Hello, 

The project isn't abandoned. We'll provide a new update by the end of the month (release v1.1 stable).

**Comment by boblowski** [comment]
Hi farfou, 

Thank you for the update, that is great news. I'm looking forward to the 1.1 release.
