### ISSUE TITLE
Kimios Web Client German translation

### ISSUE THREAD

**Issue by sce144** [kimios/kimios#4]
Hi,

so far, kimios does not support German translation files. If you are interessted I might be able to provide you by an appropriate translation.

**Comment by itechmaga** [comment]
Hallo, 
Ich wäre sehr intressiert an der Deutschen Übersetzung
---
Hello,
I would be very interested in the German translation

**Comment by devtom30** [comment]
Hello,
You are right, no german file. We are very interested in a german translation. 
You can find the translation files at this path kimios/kimios-webclient/src/main/resources/org/kimios/i18n/.
Copy the file "client_en.properties" under a file named "client_ge.properties" and do the german translations in it.
Then do a merge request and we will integrate it to the source files.
Regards
Thomas
