### ISSUE TITLE
Could I know where I compile the code is better

### ISSUE THREAD

**Issue by lxia-hub** [kimios/kimios#43]

**Comment by devtom30** [comment]
Do you want to compile the code ?

**Comment by lxia-hub** [comment]
yeah, try to update something, Is it possible?

**Comment by devtom30** [comment]
Yes, it's possible. You have to clone that git repository, checkout the default branch 1.2.2-SNAPSHOT, install a java development kit version 8, install maven 3 and do : maven clean install.
You have to be a java developer to do that because it requires some knowledge. Are you a java developer ?

**Comment by lxia-hub** [comment]
thanks a lot. I am not. I will try to do that.

**Comment by lxia-hub** [comment]
Could I ask a question. I've tried some ways but it still cannot be resolved.
![image](https://user-images.githubusercontent.com/69227782/108580857-64363800-7368-11eb-9d4f-486284cef565.png)

![image](https://user-images.githubusercontent.com/69227782/108580884-8039d980-7368-11eb-95c8-6663de304c31.png)

what is really jar package for javax.jws and Webservice.  Thanks a lot.

**Comment by devtom30** [comment]
You must use Oracle Java Development Kit 8. Is it the version you are using ?

**Comment by lxia-hub** [comment]
Oracle Java Development Kit 8 is:
![image](https://user-images.githubusercontent.com/69227782/108797342-f2f3c080-75c5-11eb-81e4-03a6f00f22fc.png)
![image](https://user-images.githubusercontent.com/69227782/108797459-32baa800-75c6-11eb-8eee-3259c22baf02.png)
Is it right?

**Comment by devtom30** [comment]
You have JRE, Java Runtime Environment. With it you can run java applications. 
Now you need to compile java source code, so you need Java Development Kit, also said JDK.

**Comment by devtom30** [comment]
In your console, try that: javac -version
What do you have ?

**Comment by lxia-hub** [comment]
Got it. Thanks a lot. I will do one more try.

**Comment by lxia-hub** [comment]
Sorry. Now the Java Development Kit seems OK.
C:\Users\hk_validation>java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

C:\Users\hk_validation>javac -version
javac 1.8.0_281

But it has the same issue about javax.jws and Webmethod and Webparam. what is the jar package they use?

**Comment by lxia-hub** [comment]
Excuse me. Could you tell me your support service? I cannot get contact with the  commercial@kimios.com and sales@teclib.com

**Comment by lxia-hub** [comment]
The import org.kimios.utils.version cannot be resolved. how to solve this problem?

**Comment by devtom30** [comment]
in kimios-utils, create file src/main/java/org/kimios/utils/version/Version.java with this content:

```
package org.kimios.utils.version;

public class Version {

    public static String KIMIOS_VERSION ="";
    public static String MAVEN_BUILD_NUMBER = "";
    public static String MAVEN_PROJECT_VERSION = "";
    public static String JAVA_VM_VERSION = "";
    public static String JAVA_VERSION = "";
    public static String MAVEN_BUILD_TIMESTAMP = "";
    public static String KIMIOS_DISTRIBUTION = "%KIMIOS_DISTRIBUTION%";
}

```

**Comment by lxia-hub** [comment]
Thanks a lot. Could you mind telling me where is the entrance of the home page(web) in the code?
