### ISSUE TITLE
http://IP/kimios cannot show log in page any more

### ISSUE THREAD

**Issue by lxia-hub** [kimios/kimios#45]
![image](https://user-images.githubusercontent.com/69227782/110887467-58191700-8325-11eb-8c88-4e4d7064ea66.png)

When input the URL  http://IP/kimios, the page is showing like that. there is no log in label. how can I troubleshooting the issue?

12 Mar 2021 18:15:02 WARN  org.apache.cxf.bus.spring.OldSpringSupport - Import of META-INF/cxf/cxf-extension-soap.xml has been deprecated and is unnecessary.
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.events.EventHandlerManager - Adding event handler org.kimios.kernel.index.solr.SolrIndexer
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.events.EventHandlerManager - No custom event handlers defined
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Loading filters configuration ...
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Index filters Loaded
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [xls] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [ppsx] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [xlsx] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [pdf] --> [org.kimios.kernel.index.filters.PDFFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [odp] --> [org.kimios.kernel.index.filters.ODTFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [xml] --> [org.kimios.kernel.index.filters.TXTFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [pps] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [ods] --> [org.kimios.kernel.index.filters.ODTFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [ppt] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [pptx] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [odt] --> [org.kimios.kernel.index.filters.ODTFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [txt] --> [org.kimios.kernel.index.filters.TXTFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [doc] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [html] --> [org.kimios.kernel.index.filters.TXTFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [docx] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.index.FiltersMapper - [kimios Indexer] - Extension : [vsd] --> [org.kimios.kernel.index.filters.OfficeFilter]
12 Mar 2021 18:15:02 INFO  org.kimios.kernel.dms.metafeeds.MetaFeedManager - [kimios MetaFeed Manager] - Starting ...
12 Mar 2021 18:15:03 INFO  org.reflections.Reflections - Reflections took 305 ms to scan 8 urls, producing 157 keys and 501 values 
12 Mar 2021 18:15:03 INFO  org.kimios.kernel.dms.metafeeds.MetaFeedManager - [kimios MetaFeed Manager] - Started : 2 loaded and available.
12 Mar 2021 18:15:03 INFO  org.kimios.kernel.deployment.DataInitializerCtrl - Database Initialized.
12 Mar 2021 18:15:03 ERROR org.kimios.kernel.repositories.RepositoryManager - Repository error: no default repository set. Setting to default
12 Mar 2021 18:15:04 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /rest/
12 Mar 2021 18:15:04 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}SecurityService from class org.kimios.webservices.SecurityService
12 Mar 2021 18:15:04 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /SecurityService
12 Mar 2021 18:15:04 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}AdministrationService from class org.kimios.webservices.AdministrationService
12 Mar 2021 18:15:04 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /AdministrationService
12 Mar 2021 18:15:04 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}StudioService from class org.kimios.webservices.StudioService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /StudioService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}DocumentService from class org.kimios.webservices.DocumentService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /DocumentService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}DocumentVersionService from class org.kimios.webservices.DocumentVersionService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /DocumentVersionService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}FolderService from class org.kimios.webservices.FolderService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /FolderService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}WorkspaceService from class org.kimios.webservices.WorkspaceService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /WorkspaceService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}SearchService from class org.kimios.webservices.SearchService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /SearchService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}NotificationService from class org.kimios.webservices.NotificationService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /NotificationService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}LogService from class org.kimios.webservices.LogService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /LogService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}InformationService from class org.kimios.webservices.InformationService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /InformationService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}ExtensionService from class org.kimios.webservices.ExtensionService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /ExtensionService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}RuleService from class org.kimios.webservices.RuleService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /RuleService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}ReportingService from class org.kimios.webservices.ReportingService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /ReportingService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}FileTransferService from class org.kimios.webservices.FileTransferService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /FileTransferService
12 Mar 2021 18:15:05 INFO  org.apache.cxf.service.factory.ReflectionServiceFactoryBean - Creating Service {http://kimios.org}ConverterService from class org.kimios.webservices.ConverterService
12 Mar 2021 18:15:05 WARN  org.apache.cxf.aegis.type.java5.Java5TypeCreator - Could not map TypeVariable named V from java.util.List<V> with initial mapping {V=java.util.List<V>, K=class java.lang.String} to a known class.  Using Object.
12 Mar 2021 18:15:05 WARN  org.apache.cxf.aegis.type.java5.Java5TypeCreator - Could not map TypeVariable named V from java.util.List<V> with initial mapping {V=java.util.List<V>, K=class java.lang.String} to a known class.  Using Object.
12 Mar 2021 18:15:05 WARN  org.apache.cxf.aegis.type.java5.Java5TypeCreator - Could not map TypeVariable named V from java.util.List<V> with initial mapping {V=java.util.List<V>, K=class java.lang.String} to a known class.  Using Object.
12 Mar 2021 18:15:05 INFO  org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /ConverterService
12 Mar 2021 18:15:05 INFO  org.kimios.kernel.configuration.Starter -  **** Kimios **** Initializing context ...
12 Mar 2021 18:15:05 INFO  org.kimios.deployer.web.AppContextLoaderListener - Kimios started
Mar 12, 2021 6:15:05 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /opt/kimios-bundle-1.0/webapps/ROOT.war
12 Mar 2021 18:15:07 INFO  org.kimios.core.CoreInitializer - kimios - Starting Client
12 Mar 2021 18:15:07 INFO  org.kimios.core.FileCleaner - Cleaning kimios-tmp ... 
12 Mar 2021 18:15:07 INFO  org.kimios.core.FileCleaner - Nothing to clean.
Mar 12, 2021 6:15:07 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-9999"]
Mar 12, 2021 6:15:07 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-10000"]
Mar 12, 2021 6:15:07 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Mar 12, 2021 6:15:07 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 20281 ms
12 Mar 2021 18:15:07 INFO  org.kimios.kernel.security.SessionCleaner - [SESSIONCLEANNER] - Starting ...
12 Mar 2021 18:15:07 INFO  org.kimios.kernel.security.SessionManager - [kimios - SESSION MANAGER Initialization:0 have been re-loaded!
12 Mar 2021 18:15:07 INFO  org.kimios.kernel.security.SessionCleaner - [SESSIONCLEANNER] - Starded !

**Comment by devtom30** [comment]
Hi,
Try : http://IP:PORT
Regards
