### ISSUE TITLE
Is the project still alive ?

### ISSUE THREAD

**Issue by jri-sp** [kimios/kimios#5]
Hello,

We're acually looking for a DMS software. Kimios seems a good one, but there is not commit since 2015.

It is an abandonned project ?

Regards,

**Comment by kimios** [comment]
Hello, 

Thanks a lot for your interest about Kimios. 
Not at all. We just have been away, working on the project refactoring.

The last snapshot branch has been sync, and the stable release will happen very soon.

Regards,
