### ISSUE TITLE
Problem in the identification page

### ISSUE THREAD

**Issue by ykasdi** [kimios/kimios#8]
Hello, I have a problem in the identification page, I can not identify and I can not find the domain kimios.
![06-10-2016 17-42-21](https://cloud.githubusercontent.com/assets/23259888/20878856/fbfcd1c4-bac8-11e6-80d1-1e7764f801ce.png)

you can help me please.

**Comment by bollis** [comment]
I am also having this problem. There is no documentation on how to set the domain name or what to do here.

I have emailed the support email address many times but no reply. The forums seem to be dead - no new posts in years and it seems that new content is disabled. 

Have you managed to resolve this?

**Comment by farfou** [comment]
Hi, 

The forum is dead yes, for now. 

Regarding the problem you met, it's related to an incorrect deployment, and/or the database connexion.
First, could you download the last bundle (1.1-SNAPSHOT version) ? 

Then, to start the deployment : 
- launch Kimios Server using the script kimios.sh : 

`kimios.sh start`


- access to : 

`http://<serverip>:9999/kimios`

A deployment wizard will be shown. Kimios support PostgreSQL, MySQL, SQL Server, and Oracle Database. 
The wizard let you create a database directly, or you can use an already existing one.


Regards,

**Comment by ykasdi** [comment]
Hi,
I solved the problem,

It is necessary to make sure:
- that tomcat server is switched off and java process is non-existent, For
example, use the 'killall java' command.
- remove kimios.pid file at the root of kimios bundle
- restart the bundle (via ./kimios.sh start)

Regards,


*Très cordialement.*


*[image: dz]*

*Yassir KASDI |Consultant Système et Réseaux | INOVTEAM *

10, Rue de la Liberté - Casablanca 20120
*Tel*: 05 22 54 47 60 | *GSM *: 06 19 07 75 18

E-mail: ykasdi@inovteam.com *|* Website: www.inovteam.com

*Nous intégrons aussi les solutions suivantes : *
<http://www.inovteam.com/>

<http://www.inovteam.com/> <http://inovteam.com/solution-erp/> [image:
http://inovteam.com/docuged/] <http://inovteam.com/docuged/>
<http://inovteam.com/solution-crm/> [image:
http://inovteam.com/infogerance-glpi/]
<http://inovteam.com/infogerance-glpi/>


*Pensez à l'environnement avant d'imprimer ce courrier !*

<http://inovteam.com/infogerance-glpi/>
<http://inovteam.com/infogerance-glpi/>


2017-02-01 8:36 GMT+00:00 Farf <notifications@github.com>:

**Comment by NicolasScarrone** [comment]
Hello, how are you?
Question: Is kimios compatible with mariadb?
Thanks.
