### ISSUE TITLE
Kimios webpage links are broken

### ISSUE THREAD

**Issue by FooBarTrixibell** [kimios/kimios#9]
The links to download Kimios from the webpage results in a 'The requested resource was not found Http://www.kimios.com/web/guest/null' both from anonymous download and giving details.

http://demo.kimios.com/ fails to load the authentication fields -

SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
File: ext-base.js, Line: 7, Column: 1533
SCRIPT5007: Unable to get property 'ComboBox' of undefined or null reference
File: AuthenticationSourceField.js, Line: 18, Column: 1
SCRIPT5007: Unable to get property 'FormPanel' of undefined or null reference
File: FormPanel.js, Line: 17, Column: 1
SCRIPT438: Object doesn't support property or method 'onReady'
File: login.js, Line: 17, Column: 1

**Comment by clc-chris** [comment]
Any updates on this issue?

**Comment by devtom30** [comment]
Hello,
Thank you for reporting the problem.
We will solve this problem soon.
